name: app
on: [push]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2
      
      - name: build      
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn build
      
      - name: deploy
      - uses: JamesIves/github-pages-deploy-action@4.1.4
      - with:
          branch: gh-pages 
          folder: build
      
