name: app
on: [push]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: |
          actions/checkout@v2
          actions/setup-node@v2
      
      - name: build                     
        run: |
          yarn install
          yarn build
      
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages 
          folder: build
      
